Repository Kibibit/gitflow-hotfix, pull requests merged in 2022-08, with the labels that each got.

#143 feat(pr): add review approval for created PR
  src/github-communicator.ts
Labels: PR: unreviewed

#144 Release/new main release yo
  CHANGELOG.md
  README.md
  action.yml
  dist/index.js
  dist/index.js.map
  lib/github-communicator.js
  lib/main.js
  src/github-communicator.ts
  src/main.ts
Labels: PR: unreviewed

#145 fix(pr): make reviewer a different token input
  action.yml
  src/github-communicator.ts
Labels: PR: unreviewed, hotfix

#146 [AUTO] fix(pr): make reviewer a different token input
  CHANGELOG.md
  action.yml
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  dist/sourcemap-register.js
  lib/github-communicator.js
  lib/main.js
  src/github-communicator.ts
  src/main.ts
Labels: PR: unreviewed, hotfix, auto-created

#147 fix(input): pass reviewerToken into the main process
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  dist/sourcemap-register.js
  lib/github-communicator.js
  lib/main.js
  src/main.ts
Labels: PR: unreviewed, hotfix
